### ISSUE TITLE
sakamomo family apiに繋ぎこむ

### ISSUE THREAD

**Issue by sakamoto-family-smile** [sakamoto-family-smile/ChatVRM#4]
# 対応内容

* ログイン処理を実装（画面を作るかは別途検討）
* チャットに対するリクエストを送る処理の実装

**Comment by sakamoto-family-smile** [comment]
専用のブランチを切っておく

**Comment by sakamoto-family-smile** [comment]
typescriptでログイン処理作らないとか・・

**Comment by sakamoto-family-smile** [comment]
ログイン + token付与してのリクエストサンプル

https://zenn.dev/straydog/articles/8b2fa5b9f781bd45b7cf
https://zenn.dev/rescuenow/articles/1f166a0c348ae3
https://cloud.google.com/run/docs/tutorials/identity-platform?hl=ja

上記が参考になりそう

**Comment by sakamoto-family-smile** [comment]
https://qiita.com/Takuya__/items/bfedff7faef76f17d970
ログイン画面、上記のような感じのものを作りたい

**Comment by sakamoto-family-smile** [comment]
https://zenn.dev/y_ta/articles/b1908ec6af6819
ログイン時にローディング画面も欲しい

**Comment by sakamoto-family-smile** [comment]
https://zenn.dev/hakoten/articles/032512f59d243e
suspenseについて

**Comment by sakamoto-family-smile** [comment]
https://qiita.com/seira/items/8a170cc950241a8fdb23
useCallbackについて

なるほど、処理をキャッシュ化しておいて、指定したパラメーター（メモ化？）が変わった場合のみ、再度処理が実行される感じか

**Comment by sakamoto-family-smile** [comment]
buttonをクリックされて、処理がおわるまでローディング画面を出したいんだけど、
suspenseだと子要素の処理がおわるまで出す感じで、うまくできるのか・・？

react, next周りの知識なさすぎて、きついな笑

**Comment by sakamoto-family-smile** [comment]
https://ja.react.dev/reference/react/Suspense
suspenseについて（公式ドキュメント）

↓

https://codesandbox.io/p/sandbox/7hzg5z
お、このサンプルが結構やりたいことに近いかも

**Comment by sakamoto-family-smile** [comment]
うーむ、、下記エラーになった。。process is not defined・・

```
framework-3671d8951bf44e4e.js:9 ReferenceError: process is not defined
    at ev (index-78adf2649739fd6e.js:1:26707)
    at ab (framework-3671d8951bf44e4e.js:9:60915)
    at i (framework-3671d8951bf44e4e.js:9:119473)
    at oO (framework-3671d8951bf44e4e.js:9:99112)
    at framework-3671d8951bf44e4e.js:9:98979
    at oF (framework-3671d8951bf44e4e.js:9:98986)
    at ox (framework-3671d8951bf44e4e.js:9:95738)
    at oS (framework-3671d8951bf44e4e.js:9:94293)
    at x (framework-3671d8951bf44e4e.js:33:1373)
    at MessagePort.T (framework-3671d8951bf44e4e.js:33:1903)
```

**Comment by sakamoto-family-smile** [comment]
email, password情報が入力した内容が変数に入ってこない・・。

**Comment by sakamoto-family-smile** [comment]
そうか、useCallbackはどの値が変更されたら再度更新されるか？を変数設定しておく必要がある。
それが不足していた。

↓

geminiの回答
```
1. useCallback の依存配列が正しくない

useCallback は、依存配列に指定された値が変更された場合にのみ新しい関数を生成します。もし、useState の変数を更新するために必要な値が依存配列に含まれていない場合、useCallback は古い関数を再利用し、その結果、useState の変数は更新されません。

解決策: useState の変数を更新するために必要な値を useCallback の依存配列に追加してください。
```

**Comment by sakamoto-family-smile** [comment]
ブラウザ経由のため、下記のエラーで怒られた

```
Access to fetch at 'https://sakamomo-family-app.com/bot' from origin 'https://sakamomo-family-vr-front-749925056555.asia-northeast1.run.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

CORS対応がバックエンドサーバー側で必要

**Comment by sakamoto-family-smile** [comment]
https://fastapi.tiangolo.com/ja/tutorial/cors/

**Comment by sakamoto-family-smile** [comment]
FastAPI側にCORS対応してもダメで、IAP側にもCORS対応が必要そう

**Comment by sakamoto-family-smile** [comment]
お、x-goog-iap-jwt-assertionにトークンを付与する必要がある？

**Comment by sakamoto-family-smile** [comment]
まだ解消せず

**Comment by sakamoto-family-smile** [comment]
下記geminiからのレスポンス

```
承認済みのリダイレクト URI は、OAuth 2.0 フローにおいて、認証サーバーが認証コードや ID トークンを返す際に使用する URL です。

今回のケースでは、クライアント（JavaScript）は Identity Platform で認証を行い、ID トークンを取得します。この ID トークンは、クライアントから直接 Cloud Run サービスに送信されます。Cloud Run サービスは IAP で保護されているため、IAP が ID トークンを検証し、クライアントを認証します。

つまり、OAuth 2.0 フローにおいて、認証サーバー（Identity Platform）からクライアント（JavaScript）にリダイレクトされることはありません。

そのため、承認済みのリダイレクト URI に Cloud Run サービスの URL を指定する必要はありません。 Load Balancer の URL でも問題ありませんし、実際には 承認済みのリダイレクト URI は空欄でも構いません。

重要なのは、承認済みの JavaScript オリジン に JavaScript クライアントのオリジンが正しく設定されていることです。

もし、承認済みのリダイレクト URI に Cloud Run サービスの URL を設定している場合は、空欄にするか、Load Balancer の URL に変更してみてください。

それでも CORS エラーが解消されない場合は、他の原因を調査する必要があります。
```

**Comment by sakamoto-family-smile** [comment]
https://zenn.dev/quantum/articles/afec11e5ce6a9a
あれ、ロードバランサーでCORS用のヘッダー付与が必要なのでは？

**Comment by sakamoto-family-smile** [comment]
お、load balancerのログ、401（Unauthorized）になっているのがわかった
クエリは下記

```
resource.type="http_load_balancer"
```

ログ
```json
{
  "insertId": "1q3huofj2cx3r",
  "jsonPayload": {
    "cacheDecision": [
      "RESPONSE_HAS_CONTENT_TYPE",
      "CACHE_MODE_USE_ORIGIN_HEADERS"
    ],
    "backendTargetProjectNumber": "projects/749925056555",
    "@type": "type.googleapis.com/google.cloud.loadbalancing.type.LoadBalancerLogEntry",
    "securityPolicyRequestData": {
      "remoteIpInfo": {
        "regionCode": "JP"
      },
      "tlsJa3Fingerprint": "821dcaf2e0a261c4052caa207fd5081d"
    },
    "enforcedSecurityPolicy": {
      "outcome": "ACCEPT",
      "rateLimitAction": {
        "outcome": "RATE_LIMIT_THRESHOLD_CONFORM",
        "key": "114.163.84.9"
      },
      "priority": 2147483646,
      "name": "security-policy-for-backend-service-sakamomo-family-api-backend",
      "configuredAction": "THROTTLE"
    },
    "statusDetails": "handled_by_identity_aware_proxy",
    "remoteIp": "114.163.84.9"
  },
  "httpRequest": {
    "requestMethod": "OPTIONS",
    "requestUrl": "https://sakamomo-family-app.com/bot",
    "requestSize": "425",
    "status": 401,
    "responseSize": "188",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "remoteIp": "114.163.84.9",
    "referer": "https://sakamomo-family-vr-front-749925056555.asia-northeast1.run.app/",
    "latency": "0.018289s"
  },
  "resource": {
    "type": "http_load_balancer",
    "labels": {
      "backend_service_name": "sakamomo-family-api-backend",
      "zone": "global",
      "project_id": "youyaku-ai",
      "url_map_name": "sakamomo-family-api-lb",
      "forwarding_rule_name": "sakamomo-family-api-lb-ip-https",
      "target_proxy_name": "sakamomo-family-api-lb-target-proxy"
    }
  },
  "timestamp": "2024-11-03T13:23:25.407233Z",
  "severity": "WARNING",
  "logName": "projects/youyaku-ai/logs/requests",
  "trace": "projects/youyaku-ai/traces/69ed09c4eeeb896c0c91de793448c766",
  "receiveTimestamp": "2024-11-03T13:23:26.481441385Z",
  "spanId": "5cf6fc5449d82d6d"
}
```

**Comment by sakamoto-family-smile** [comment]
geminiからの回答。普通に勉強になるな。

```
ログ情報ありがとうございます。

Load Balancer から 401 (Unauthorized) が返されているということは、IAP がクライアントを認証できていないことを示しています。

考えられる原因としては、以下の点が挙げられます。

x-goog-iap-jwt-assertion ヘッダーが正しく設定されていない

JavaScript クライアントから送信されるリクエストに、x-goog-iap-jwt-assertion ヘッダーが含まれているか確認してください。
ヘッダーに設定されている ID トークンが、Identity Platform から取得した正しいものであるか確認してください。
ID トークンが有効期限内であることを確認してください。
IAP の OAuth クライアント設定が正しくない

IAP の OAuth クライアントの 承認済みの JavaScript オリジン に、JavaScript クライアントのオリジンが正しく設定されているか確認してください。
承認済みのリダイレクト URI は、今回のケースでは空欄で問題ありません。
IAP の認証設定が正しくない

IAP で、Cloud Run サービスに対する認証方法が正しく設定されているか確認してください。
特に、OAuth 2.0 を使用して認証を行うように設定されていることを確認してください。
Load Balancer の設定が正しくない

Load Balancer が IAP を経由するように正しく設定されているか確認してください。
Load Balancer のヘルスチェック設定が正しく、Cloud Run サービスが正常に動作していることを確認してください。
CORS の設定が正しくない

IAP の OAuth クライアントの 承認済みの JavaScript オリジン に加えて、FastAPI 側でも CORS の設定が必要です。CORSMiddleware を使用して、JavaScript クライアントのオリジンを許可するように設定してください。
ログからわかること

httpRequest.requestMethod が OPTIONS になっていることから、これはプリフライトリクエストです。
httpRequest.status が 401 になっていることから、IAP がプリフライトリクエストを認証できていません。
jsonPayload.statusDetails が handled_by_identity_aware_proxy になっていることから、リクエストは IAP によって処理されています。
これらの情報から、IAP の認証設定または CORS 設定に問題がある可能性が高いと考えられます。

上記の点を順番に確認し、問題を特定してください。
```

**Comment by sakamoto-family-smile** [comment]
iapのログを見たいが、resource type=iapにしても、でてこない・・

**Comment by sakamoto-family-smile** [comment]
おそらくだが、IAPがプリフライトリクエスト（option）を認証できていない気がする。
これはどうやって調べるか

**Comment by sakamoto-family-smile** [comment]
あれ、、http側にリダイレクトされている？
※バックエンドサービスが設定されていない

```
backend_service_name: ""
forwarding_rule_name: "sakamomo-family-api-lb-ip-http2"
project_id: "youyaku-ai"
target_proxy_name: ""
url_map_name: ""
zone: "global"
```

↓

CORSエラーが起因になっていそう

**Comment by sakamoto-family-smile** [comment]
https://cloud.google.com/iap/docs/customizing?hl=ja#allowing_http_options_requests_cors_preflight

**Comment by sakamoto-family-smile** [comment]
access_settings.cors_settings.allow_http_optionsをtrueにする必要があるかも
IAPの設定画面？

**Comment by sakamoto-family-smile** [comment]
IAPの設定画面で、「HTTPオプションを有効にする」をチェック入れると、プリフライトリクエストをiAP側で受け取れるようになった。

Authorizationヘッダにトークンを入れたら、バックエンド側までリクエストがきた！
しかし、まだ422エラーになっている

**Comment by sakamoto-family-smile** [comment]
やっと、バックエンドからもレスポンスが帰ってきて、正常動作した！

**Comment by sakamoto-family-smile** [comment]
#7 でブランチにマージ
